### ISSUE TITLE
Potential typo in the paper

### ISSUE THREAD

**Issue by pkhungurn** [sony/ctm#1]
This comment is based on the arXiv PDF (https://arxiv.org/pdf/2310.02279.pdf) that I downloaded on 2023/10/30.

The 3rd page says "Here, $E_{p_{t0}(\mathbf{x}|\mathbf{x}_t)}$ is the denoiser function, an alternative expression for the score function $\nabla \log p_t(\mathbf{x}_t)$." The authors cite Bradley Efron's paper on Tweedie's formula as a justification.

![ctm-typo](https://github.com/sony/ctm/assets/25254747/4baa0d5a-778a-42fa-84fa-1d968c9d5f57)

I think this is wrong. Assuming that $E_{p_{t0}(\mathbf{x}|\mathbf{x}_t)} = \nabla \log p_t(\mathbf{x}_t)$ as the above sentence said, we would have that
```math 
\frac{\mathrm{d}\mathbf{x}_t}{\mathrm{d}t} = \frac{\mathbf{x}_t - E_{p_{t0}(\mathbf{x}|\mathbf{x}_t)}[\mathbf{x}|\mathbf{x}_t] }{t} = \frac{\mathbf{x}_t - \nabla \log p_t(\mathbf{x}_t) }{t} \neq - t \nabla \log p_t(\mathbf{x}_t).
```
Instead, it should have been 
```math
E_{p_{t0}(\mathbf{x}|\mathbf{x}_t)}[\mathbf{x}|\mathbf{x}_t] = \mathbf{x}_t + t \nabla \log p_t(\mathbf{x}_t),
```
which will make the equation above holds.

Indeed, the above statement also agree with Tweedie's formula, which states that
> If $\mathbf{x}$ and $\mathbf{y}$ are random variables such that $\mathbf{y} = \mathbf{x} + \boldsymbol{\xi}$ where $\boldsymbol{\xi} \sim \mathcal{N}(\mathbf{0},\sigma^2 I)$, then $$E[\mathbf{y}|\mathbf{x}] = \mathbf{x} + \sigma^2 \nabla \log p(\mathbf{x}).$$

Because $\mathrm{d} \mathbf{x}_t = \sqrt{2t}\, \mathrm{d} \mathbf{w}$, we have that $p(\mathbf{x}_t | \mathbf{x}_0) \sim \mathcal{N}(0, tI)$. In other words, $\mathbf{x}_t = \mathbf{x}_0 + \boldsymbol{\xi}$ where $\boldsymbol{\xi} \sim \mathcal{N}(0, tI)$. Tweedie's formula thus gives
```math
E_{p_{t0}(\mathbf{x}|\mathbf{x}_t)}[\mathbf{x}_0|\mathbf{x}_t] = E[\mathbf{x}_0|\mathbf{x}_t] = \mathbf{x}_t + t \nabla \log p(\mathbf{x}_t) =  \mathbf{x}_t + t \nabla \log p_t(\mathbf{x}_t).
```

**Comment by ChiehHsinJesseLai** [comment]
Hi @pkhungurn,

Thank you for your careful read of our paper. 
Please kindly notice that we were not saying the denoiser "is" the score function but we say it is an alternative expression.

To avoid confusion, we will make the statement clearer by saying:

![image](https://github.com/sony/ctm/assets/118706858/2a7c7f4d-23fb-40cd-b455-2f3b5f3b6887)

**Comment by JiePKU** [comment]
> Hi @pkhungurn,
> 
> Thank you for your careful read of our paper. Please kindly notice that we were not saying the denoiser "is" the score function but we say it is an alternative expression.
> 
> To avoid confusion, we will make the statement clearer by saying:
> 
> ![image](https://private-user-images.githubusercontent.com/118706858/291471335-2a7c7f4d-23fb-40cd-b455-2f3b5f3b6887.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzE4MzUsIm5iZiI6MTcxNzEzMTUzNSwicGF0aCI6Ii8xMTg3MDY4NTgvMjkxNDcxMzM1LTJhN2M3ZjRkLTIzZmItNDBjZC1iNDU1LTJmM2I1ZjNiNjg4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwNDU4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTUzMzI4MTRiNjU2MWI0OTYwOGMxMzI5NDRmMzUzMWUwN2U0MDc2ZTMzNTk1ZmVkOGY1ZDliOWRhOTdlYjEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r8iUsvariJZbQY5pkMFiHMnomdio8QmeDLW71fFDzFM)

Hi, @ChiehHsinJesseLai , it seems that this equation 
![image](https://github.com/sony/ctm/assets/105037503/ad4df5f9-f263-4f7b-b176-f0fa2bb61c4a)
 is not reasonable when we substitute it in the second equation.  
![image](https://github.com/sony/ctm/assets/105037503/ef42cfbc-546b-45d5-8a09-2c5f4cf9d4ee)
Is there anything wrong? or something I miss?
