### ISSUE TITLE
checkpoints not available

### ISSUE THREAD

**Issue by quantumiracle** [sony/ctm#4]
Hi, 

The checkpoints link in readme requires access to google drive. 

Thanks

**Comment by ChiehHsinJesseLai** [comment]
Hi,

Thanks for brining this up.
Could you please check if it works now?

Thanks

**Comment by quantumiracle** [comment]
Thanks it works now. 

Btw, do we have the checkpoints for Cifar10 as well? It only contains files for Imagenet. It's appreciated to also upload checkpoints for Cifar10.

Thanks

**Comment by ChiehHsinJesseLai** [comment]
Hello,

Sorry for my late response.
We will release checkpoint for CIFAR-10 around April, in the co-first author's (Dongjun Kim) github page. 
Please kindly stay tuned.
