### ISSUE TITLE
Mismatch between QKVFlashAttention and QKVAttentionLegacy

### ISSUE THREAD

**Issue by paulhuangkm** [sony/ctm#5]
Dear authors,

I am working with V100 GPUs, and unfortunately flash attention does not support V100. I noticed that the dimension manipulations in QKVFlashAttention and QKVAttentionLegacy are different, which makes the provided checkpoints not working on V100 GPUs (or with QKVAttentionLegacy in general).

To resolve this issue, I have updated the dimension manipulation of QKVAttentionLegacy and also included xformers scaled product attention as an additional option. Should I create a pull request? (Left image: original QKVAttentionLegacy, Right image updated QKVAttentionLegacy)
<img src="https://github.com/sony/ctm/assets/71301459/b30d4424-4591-41c8-967b-7eadd9493fb6" width="200"> <img src="https://github.com/sony/ctm/assets/71301459/9008b25b-44d6-4068-a1b9-a8a175884fe9" width="200">

Thanks!

**Comment by Kim-Dongjun** [comment]
Hi Paul,

That looks fantastic to us. We previously tried to solve this issue but failed due to time constraints.
It would be really appreciated if you could create a pull request!

Best,
Dongjun

**Comment by paulhuangkm** [comment]
Hi @Kim-Dongjun ,

I have created a pull request at #6.

Best,
Paul

**Comment by ChiehHsinJesseLai** [comment]
Hi @paulhuangkm,

Thanks for the request. Now merged!

Best,
Chieh-Hsin (Jesse)
