### ISSUE TITLE
Why using the retrained checkpoint "edm-imagenet-64x64-cond-adm.pkl" instead of the original EDM checkpoint "edm_imagenet64_ema.pt" as the teacher?

### ISSUE THREAD

**Issue by zhengkw18** [sony/ctm#7]
As I understand, "edm-imagenet-64x64-cond-adm.pkl" adopts the architecture of ADM, which is different from EDM. Which one is better when used as the teacher of distillation?

**Comment by Kim-Dongjun** [comment]
In the architectural side, "edm-imagenet-64x64-cond-adm.pkl" could be different from the original EDM. The major reason of using this "pkl" checkpoint is to initialize the model with a pre-trained checkpoint. Either model is okay to use as the teacher.
